version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "angular-example-statics"
    BUILD_FOLDER: "angular-example-artifacts"
    BUCKET_FOR_INDEX: "s3://angular-example-artifacts/VersionIndexes"
    BUILD_ENV: "prod"
    #webhookURL: "https://hooks.slack.com/services/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"
  secrets-manager:
    FONTAWESOME_NPM_AUTH_TOKEN: arn:aws:secretsmanager:us-east-1:478997086104:secret:testKey
    testToken2: arn:aws:secretsmanager:us-east-1:478997086104:secret:testSecret-A6bQkf
phases:
  install:
    commands:
      - npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && \
        npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_NPM_AUTH_TOKEN
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - chmod a+x exec.sh
      - ./exec.sh
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
 # base-directory: 'dist*'
 # discard-paths: yes
